export const mcpToolCatalog = [
  { name: 'system_health', mode: 'read-only', description: 'Minimal non-sensitive MCP control-plane health snapshot.' },
  { name: 'list_projects', mode: 'read-only', description: 'List registered local project workspaces and IDs.' },
  { name: 'project_info', mode: 'read-only', description: 'Return metadata for one registered local project.' },
  { name: 'project_access_status', mode: 'read-only', description: 'Inspect effective project capability availability, policy denial and permission ambiguity without exposing bearer session IDs.' },
  { name: 'project_readiness', mode: 'read-only', description: 'Inspect dependency/toolchain/config readiness before coding so environment failures are separated from source failures.' },
  { name: 'prepare_workspace', mode: 'write+execute', description: 'Install missing declared dependencies through structured recipes and capture baseline verification before edits.' },
  { name: 'workspace_bootstrap', mode: 'read-only', description: 'Bootstrap project metadata, access manifest, task/preview profiles, scripts, skills and Verification Router strategy.' },
  { name: 'list_task_profiles', mode: 'read-only', description: 'Auto-discover structured verification profiles from safe package-script aliases, ecosystem conventions, explicit MCP overrides and built-in static integrity checks.' },
  { name: 'run_task', mode: 'execute', description: 'Execute one structured task with no shell interpolation, sanitized env, timeout/output caps and tree cleanup.' },
  { name: 'list_command_recipes', mode: 'read-only', description: 'Discover dependency/install/codegen recipes plus every safe-name package.json script available to this project.' },
  { name: 'run_command_recipe', mode: 'write+execute', description: 'Run a validated project recipe or an existing safe-name package.json script without arbitrary caller shell input.' },
  { name: 'process_profiles', mode: 'read-only', description: 'Discover safe long-running package process profiles such as dev/start/serve/preview/storybook/watch.' },
  { name: 'process_list', mode: 'read-only', description: 'List runtime-owned managed project process sessions with bounded redacted logs.' },
  { name: 'process_start', mode: 'execute', description: 'Start one discovered long-running package process profile with sanitized environment and no caller shell input.' },
  { name: 'process_status', mode: 'read-only', description: 'Read one managed process state, PID and bounded redacted logs.' },
  { name: 'process_stop', mode: 'execute', description: 'Stop one runtime-owned managed process and its process tree.' },
  { name: 'git_status', mode: 'read-only', description: 'Read structured Git branch/upstream/dirty state for a repository whose root exactly matches the registered project.' },
  { name: 'git_diff', mode: 'read-only', description: 'Read bounded working-tree or staged Git diff with external diff disabled.' },
  { name: 'git_log', mode: 'read-only', description: 'Read bounded structured local Git commit history.' },
  { name: 'git_branches', mode: 'read-only', description: 'List local Git branches and upstream metadata.' },
  { name: 'git_stage', mode: 'write+execute', description: 'Stage validated project-relative paths; requires git write plus command capability.' },
  { name: 'git_unstage', mode: 'write+execute', description: 'Unstage validated project-relative paths without modifying working-tree content.' },
  { name: 'git_create_branch', mode: 'write+execute', description: 'Create and switch to one validated local Git branch.' },
  { name: 'git_switch_branch', mode: 'write+execute', description: 'Switch to one validated existing local Git branch.' },
  { name: 'git_commit', mode: 'write+execute', description: 'Commit already-staged local changes with a bounded message; never pushes.' },
  { name: 'git_restore_paths', mode: 'destructive', description: 'Restore validated project paths from Git; requires filesystem write, command and git write capabilities.' },
  { name: 'list_skills', mode: 'read-only', description: 'Discover project AGENTS/SKILL/prompt/rule files across common coding-agent formats.' },
  { name: 'read_skill', mode: 'read-only', description: 'Read one recognized project skill/instruction file.' },
  { name: 'project_guidance', mode: 'read-only', description: 'Load a bounded bundle of all recognized project coding-agent instructions/skills with scope metadata.' },
  { name: 'brain_build', mode: 'read-only', description: 'Build or incrementally refresh the bounded Project Brain index.' },
  { name: 'brain_status', mode: 'read-only', description: 'Return Project Brain state, counts, languages and index statistics.' },
  { name: 'find_symbol', mode: 'read-only', description: 'Find indexed TS/JS declarations with exact-first ranking.' },
  { name: 'symbol_references', mode: 'read-only', description: 'Return indexed TS/JS identifier references.' },
  { name: 'context_bundle', mode: 'read-only', description: 'Build a bounded graph+text ranked coding context bundle.' },
  { name: 'impact_analysis', mode: 'read-only', description: 'Trace a file/symbol to references, importers, tests and configs.' },
  { name: 'coding_cycle', mode: 'write+execute+review', description: 'Run one bounded IMPLEMENT→VERIFY→REVIEW cycle using discovered task profiles.' },
  { name: 'agent_job_create', mode: 'write', description: 'Create a persistent coding objective with bounded iteration budget.' },
  { name: 'agent_job_list', mode: 'read-only', description: 'List recent persistent coding jobs for one project.' },
  { name: 'agent_job_status', mode: 'read-only', description: 'Read persisted job state and bounded evidence for resume/recovery.' },
  { name: 'agent_job_cycle', mode: 'write+execute+review', description: 'Run one persistent coding cycle using discovered task profiles; unavailable profiles fail before state/files advance.' },
  { name: 'agent_job_complete', mode: 'write', description: 'Complete a verified job only after semantic review.' },
  { name: 'agent_job_cancel', mode: 'write', description: 'Cancel a non-terminal persistent coding job.' },
  { name: 'preview_profiles', mode: 'read-only', description: 'Discover loopback-only static/recognized framework preview profiles.' },
  { name: 'preview_list', mode: 'read-only', description: 'List runtime-owned preview sessions for one authorized project.' },
  { name: 'preview_start', mode: 'execute', description: 'Start a loopback-only project preview.' },
  { name: 'preview_status', mode: 'read-only', description: 'Read preview state and bounded redacted dev-server logs.' },
  { name: 'preview_stop', mode: 'execute', description: 'Stop a preview and its dev-server process tree.' },
  { name: 'browser_review', mode: 'execute+review', description: 'Review only a server-created preview in local Edge/Chrome with same-origin network isolation and screenshot/DOM/console evidence.' },
  { name: 'apply_and_verify', mode: 'write+execute', description: 'Apply bounded changes only after requested discovered task profiles preflight successfully.' },
  { name: 'read_file', mode: 'read-only', description: 'Read one authorized project text file with SHA-256 concurrency metadata.' },
  { name: 'read_files', mode: 'read-only', description: 'Read up to 20 authorized project text files in one bounded MCP call.' },
  { name: 'stat_path', mode: 'read-only', description: 'Stat one authorized path inside the registered project boundary.' },
  { name: 'list_files', mode: 'read-only', description: 'List bounded project files/directories without following symlinks.' },
  { name: 'search_text', mode: 'read-only', description: 'Literal case-insensitive bounded text search inside a project.' },
  { name: 'write_file', mode: 'write', description: 'Atomically create/replace a text file; existing files require current SHA-256.' },
  { name: 'append_file', mode: 'write', description: 'Atomically append text; existing files require current SHA-256.' },
  { name: 'diff_file', mode: 'read-only', description: 'Preview a bounded unified-style diff against proposed text content.' },
  { name: 'apply_patch', mode: 'write', description: 'Apply an exact text replacement guarded by SHA-256 and expected match count.' },
  { name: 'batch_patch', mode: 'write', description: 'Apply 1–20 prevalidated exact patches with best-effort rollback on failure.' },
  { name: 'copy_file', mode: 'write', description: 'Copy a bounded regular text file to a new in-project path.' },
  { name: 'move_file', mode: 'write', description: 'Move a regular text file to a new in-project path with SHA-256 guard.' },
  { name: 'delete_file', mode: 'destructive', description: 'Delete a text file with SHA-256 guard and runtime backup.' },
] as const;
