export const mcpToolCatalog = [
  { name: 'system_health', mode: 'read-only', description: 'Minimal non-sensitive MCP control-plane health snapshot.' },
  { name: 'list_projects', mode: 'read-only', description: 'List registered local project workspaces and IDs.' },
  { name: 'project_info', mode: 'read-only', description: 'Return metadata for one registered local project.' },
  { name: 'workspace_bootstrap', mode: 'read-only', description: 'Bootstrap project metadata, tools, task profiles and project skills/instructions.' },
  { name: 'list_task_profiles', mode: 'read-only', description: 'Discover structured project test/lint/typecheck/check/build/bench profiles.' },
  { name: 'run_task', mode: 'execute', description: 'Execute one structured task with no shell interpolation, sanitized env, timeout/output caps and tree cleanup.' },
  { name: 'list_skills', mode: 'read-only', description: 'Discover project AGENTS/SKILL/prompt/rule files.' },
  { name: 'read_skill', mode: 'read-only', description: 'Read one recognized project skill/instruction file.' },
  { name: 'brain_build', mode: 'read-only', description: 'Build or incrementally refresh the bounded Project Brain index.' },
  { name: 'brain_status', mode: 'read-only', description: 'Return Project Brain state, counts, languages and index statistics.' },
  { name: 'find_symbol', mode: 'read-only', description: 'Find indexed TS/JS declarations with exact-first ranking.' },
  { name: 'symbol_references', mode: 'read-only', description: 'Return indexed TS/JS identifier references.' },
  { name: 'context_bundle', mode: 'read-only', description: 'Build a bounded graph+text ranked coding context bundle.' },
  { name: 'impact_analysis', mode: 'read-only', description: 'Trace a file/symbol to references, importers, tests and configs.' },
  { name: 'apply_and_verify', mode: 'write+execute', description: 'Apply bounded changes, run structured verification tasks and roll back on failure.' },
  { name: 'read_file', mode: 'read-only', description: 'Read one authorized project text file with SHA-256 concurrency metadata.' },
  { name: 'stat_path', mode: 'read-only', description: 'Stat one authorized path inside the registered project boundary.' },
  { name: 'list_files', mode: 'read-only', description: 'List bounded project files/directories without following symlinks.' },
  { name: 'search_text', mode: 'read-only', description: 'Literal case-insensitive bounded text search inside a project.' },
  { name: 'write_file', mode: 'write', description: 'Atomically create/replace a text file; existing files require current SHA-256.' },
  { name: 'append_file', mode: 'write', description: 'Atomically append text; existing files require current SHA-256.' },
  { name: 'diff_file', mode: 'read-only', description: 'Preview a bounded unified-style diff against proposed text content.' },
  { name: 'apply_patch', mode: 'write', description: 'Apply an exact text replacement guarded by SHA-256 and expected match count.' },
  { name: 'batch_patch', mode: 'write', description: 'Apply 1–20 prevalidated exact patches with best-effort rollback on failure.' },
  { name: 'copy_file', mode: 'write', description: 'Copy a bounded regular text file to a new in-project path.' },
  { name: 'move_file', mode: 'write', description: 'Move a regular text file to a new in-project path with SHA-256 guard.' },
  { name: 'delete_file', mode: 'destructive', description: 'Delete a text file with SHA-256 guard and runtime backup.' },
] as const;
